name: Mac Release Pipeline

on:
  release:
    types: [created]
  push:
    tags:
      - v*.*.*
  workflow_dispatch: {}

jobs:
  mac:
    runs-on: macos-latest
    # needs: pypi
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt -r extra-requirements.txt
    - name: Build
      # Don't get me started. Pyinstaller doesn't properly install the target so it's registered with setuptools
      #  so you need to build locally to get the egg data to inject
      #  Not only do you have to build it you need the egg string so you have to install it I'm so mad
      run: |
        python -m build
        pip install --editable .
        pyinstaller chatdj.spec
        mv dist/chatdj dist/chatdj-mac
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: mac-build
        path: dist/chatdj-mac
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/chatdj-mac
